### PR TITLE
Update filter function to handle arrays

### LINKED ISSUE #14: Handle arrays in "main:" value of bower.json
I've been scratching my head for the last 10 minutes trying to work out why this doesn't work with [normalize.scss](https://github.com/JohnAlbin/normalize-scss). Turns out, this particular module has an array as the `main:` file, instead of a string and `.match` doesn't work on arrays.

[This is the line](https://github.com/lucasmotta/sass-module-importer/blob/master/src/index.js#L30) causing the issue is where it fails.

Example from [susy](http://susy.oddbird.net):

```
"main": "sass/_susy.scss",
```

Example from normalize.scss

```
"main": [
    "sass/_normalize.scss"
],
```

I'm using the css library for the moment, but i'd rather the sass version.

### PR DESCRIPTION
**Pull request by lachieh**
fixes #14

### CODE REVIEW

**Comment by lucasmotta** [comment]
Sorry for taking that long to review your PR.
And thanks for submitting it btw, well done for adding the tests!

**Comment by lucasmotta** [comment]
Merged on 4e8dd367978b436dedd66df8b23fd4689ae3900e

**Comment by lucasmotta** [comment]
Actually, I will have to remove part of this feature. Unfortunately when trying to publish to npm, I get an error saying that an array is now allowed as the `main` field. This only works for the `bower.json`.

Some references:
https://github.com/npm/npm/issues/9917
https://docs.npmjs.com/files/package.json#main
https://github.com/bower/spec/blob/master/json.md

**Comment by lachieh** [comment]
Yep that's fair! I only built the NPM functionality in because it was easy to do so when developing the bower side. It was just a matter of adding that test. You can safely remove that test and all the other will still pass, and the package won't have trouble publishing.

**Comment by lachieh** [comment]
This inherently creates a problem, though, in packages that only have a JS file as the main and you want to include the styles. Take [slick](https://github.com/kenwheeler/slick) for example.

Perhaps an 'overrides' object that gets passed to the importer would allow for additional/alternative files to be defined? Though in doing this, it starts to get to a point where just including the full file path in your main scss source file becomes the easier option...

**Pull request closed without merging**
